### ISSUE TITLE
Minor error in README.MD? 

### ISSUE THREAD

**Issue by pete-os** [alxwolf/ubios-cert#60]
Hi

Thanks for this - just installed it on my UDMP running UniFi OS 3.2.7. Not fully tested but looking go so far.

I have spotted one small issue - README.MD has an error in 'FIRST RUN' section:

```
cp /data/udapi-server/raddb/certs/server.pem ./raddb-server.pem
cp /data/udapi-server/raddb/certs/server-key.pem ./raddb-server-key.pem
```

 I believe `/data/udapi-server` should be `/data/udapi-config` ?

The code (`ubios-cert.env`)  does refer to `/data/udapi-config` though.

```
# Path to RADIUS server certificate
UBIOS_RADIUS_CERT_PATH='/data/udapi-config/raddb/certs'
```
Thanks

Pete

**Comment by alxwolf** [comment]
Thanks Pete, yes, you're absolutely right! will change that.

Regards Alex

**Comment by therealpaulgg** [comment]
@alxwolf sorry to necro this issue..but I am not so sure that 3.2.7 is so happy with custom certificates.

While I don't use this script specifically (I have a internal CA that I use to generate certificates for my intranet), I do at the very least replace `/data/unifi-core/config/unifi-core.crt` along with `/data/unifi-core/config/unifi-core.key`. Upon restarting unifi-core with `systemctl restart unifi-core`, the OS overwrites my custom certificates, effectively undoing my work.

My setup has been working for months and I never had to mess with keystore or the RADIUS config (raddb). I am trying to reach out to anyone who might know more. Only reason I noticed this was because my monitoring software detected it couldn't reach my router anymore...then did some digging and found this stuff out. Router must have updated at 3am causing this to break.

**Comment by alxwolf** [comment]
Oh, thanks for bringing this up. Then this will require some more investigation than anticipated...
